# Creating Arrays

## using np.array()

In [1]:
import numpy as np

arr=np.array([1, 2, 3, 4, 5])
arr2=np.array([6, 7, 8, 9, 10])
print(arr,arr2)

[1 2 3 4 5] [ 6  7  8  9 10]


## using np.arange()

In [2]:
## np.arange(start, stop, step, dtype=None)
arr3=np.arange(1, 10, 2, dtype=float)

bars=np.arange(10)
print(arr3,bars)

[1. 3. 5. 7. 9.] [0 1 2 3 4 5 6 7 8 9]



🔸 Use case: Labeling candles or simulating trade bars
🔸 Why it's important: Common when running event-based backtests

## np.linespace()

In [4]:
## np.linespace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
arr4=np.linspace(1, 10, num=5, endpoint=True, retstep=False, dtype=None)

threshold=np.linspace(0.342,0.401,6,dtype=float)
print(threshold)

[0.342  0.3538 0.3656 0.3774 0.3892 0.401 ]


🔸 Use case: Grid-search over thresholds or stop loss values
🔸 Why it's important: Used in optimization and tuning models

## ✅ 4. np.zeros() / np.ones() / np.full() for Preallocation

In [ ]:
signals=np.zeros(100)
positions = np.ones(100)
risk_array = np.full(100, 0.02)
print(signals)

🔸 Use case: Vectorized backtesting logic, pre-fill with neutral values
🔸 Why it's important: Fast initialization of signals, positions, weights

## ✅ 5. np.random for Simulating Market Behavior

In [ ]:
val=np.random.rand(5)
val2=np.random.randint(1, 10, 5)
print(val,val2)

🔸 Use case: Monte Carlo simulations or bootstrapping trades
🔸 Why it's important: Strategy stress-testing, volatility modeling

## ✅ 6. np.fromiter() for Efficient Conversions

In [ ]:
fro=np.fromiter((i*3 for i in range(10)), dtype=int) 
# print(fro)

## ✅ Bonus: OHLCV as Multi-dimensional Arrays

In [ ]:
ohlcv = np.array([
    [65200, 65400, 65100, 65300, 300],  # day 1
    [65300, 65600, 65200, 65450, 350],  # day 2
])
print(ohlcv)

🔸 Use case: Slice open, high, low, close columns individually
🔸 Why it's important: Foundation for candlestick-based strategies

# Attributes of ndarray

Understanding the attributes of an ndarray is essential to working with NumPy effectively. Here are the key attributes:

- `ndarray.shape`: Returns a tuple representing the shape (dimensions) of the array.  
- `ndarray.ndim`: Returns the number of dimensions (axes) of the array.  
- `ndarray.size`: Returns the total number of elements in the array.  
- `ndarray.dtype`: Provides the data type of the array elements.  
- `ndarray.itemsize`: Returns the size (in bytes) of each element  

In [ ]:
import numpy as np

# Simulated OHLCV data for 3 candles: [Open, High, Low, Close, Volume]
ohlcv = np.array([
    [65200, 65400, 65100, 65300, 120],
    [65300, 65600, 65250, 65550, 200],
    [65500, 65800, 65400, 65700, 180]
], dtype=np.float64)

print("Array:\n", ohlcv)

# Key ndarray attributes in algo trading context
print("\nShape (rows=candles, cols=features):", ohlcv.shape)     # (3, 5)
print("Number of dimensions (1D/2D):", ohlcv.ndim)                # 2
print("Total number of elements (3x5):", ohlcv.size)              # 15
print("Data type of elements:", ohlcv.dtype)                      # float64
print("Bytes per element:", ohlcv.itemsize)                       # 8 (for float64)


# Practice section

In [1]:
import numpy as np

In [7]:
sma=np.array([10,11,10,9,12,13,12])
sma=np.zeros((3,2))
sma=np.full((3,2), 0.5)
sma=np.random.rand(3,2)
sma=np.arange(1,10,2)
print(sma)

[1 3 5 7 9]
